### ISSUE TITLE
Dashboard - syncing and more data surfaced

### ISSUE THREAD

**Issue by catarak** [BarnesFoundation/barnes-tms-extract#10]
- [x]  When user runs the TMS -> CSV script, it needs to be appended to the bottom of the table
- [x]  When ES finishes syncing with the CSV, it needs to be updated in the table
- [x] Need to surface the number of objects in each CSV
- [x] Need to surface the number of objects in ES
- [x] Need to surface the number of objects that have been tiled

**Comment by starakaj** [comment]
K, think I've iced this ticket
