### ISSUE TITLE
Image tiling and uploading - handle copyright

### ISSUE THREAD

**Issue by catarak** [BarnesFoundation/barnes-tms-extract#17]
- [ ] upload the regular jpgs - can put this in a directory called `assets` in the same s3 bucket
- [ ] resize the regular jpgs based on copyright - when a copyright changes, can retile and upload the image
- [ ] handle copyright for image tiling

**Comment by rnackman** [comment]
@micahwalter Can you either explain this to me & @jedahan or close the issue?
