### ISSUE TITLE
csvdiff is broken if you change number of columns

### ISSUE THREAD

**Issue by catarak** [BarnesFoundation/barnes-tms-extract#9]
This is a documented issue in the library itself: https://github.com/larsyencken/csvdiff/issues/9

For us, since the number of columns won't be changing that often, we could simply dump the ES database and load it from scratch when the number of columns changes. Or we could make a PR to the library.

**Comment by starakaj** [comment]
We ended up loading the ES database from scratch (as far as we know, columns won't be changing all that often.
